.PHONY: default
default:
	pdflatex --interaction=nonstopmode AusführlicheDoku.tex

.PHONY: clean
clean:
	rm \
		*.cb \
		*.cb2 \
		*.idx \
		*.mw \
		*.out \
		*.snm \
		*.toc \
		*.log \
		*.nav \
	|| true
